//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableServiceTreaty
    {
        public int ServiceTreatyID { get; set; }
        public int ServiceTreatyServiceID { get; set; }
        public string ServiceTreatyTreatyID { get; set; }
    
        public virtual TableService TableService { get; set; }
        public virtual TableTreaty TableTreaty { get; set; }
    }
}
