//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableDistrict()
        {
            this.TableAddress = new HashSet<TableAddress>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public double DistrictSquare { get; set; }
        public int DistrictPopulation { get; set; }
        public int DistrictMetro { get; set; }
        public int DistrictBuildingType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableAddress> TableAddress { get; set; }
        public virtual TableBuildingType TableBuildingType { get; set; }
    }
}
