//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAddress
    {
        public int AddressID { get; set; }
        public int AddressCountry { get; set; }
        public int AddressCity { get; set; }
        public int AddressStreet { get; set; }
        public string AddressHouse { get; set; }
        public Nullable<int> AddressApartament { get; set; }
        public Nullable<int> AddressDistrict { get; set; }
    
        public virtual TableCity TableCity { get; set; }
        public virtual TableCountry TableCountry { get; set; }
        public virtual TableDistrict TableDistrict { get; set; }
        public virtual TableStreet TableStreet { get; set; }
    }
}
