//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableInformation
    {
        public int InformationID { get; set; }
        public int InformationRole { get; set; }
        public System.DateTime InformationDate { get; set; }
        public string InformationText { get; set; }
    
        public virtual Table_Roles Table_Roles { get; set; }
    }
}
