//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableApplication
    {
        public string ApplicationNumber { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public int ApplicationPersonalAccount { get; set; }
        public int ApplicationService { get; set; }
        public int ApplicationServiceType { get; set; }
        public int ApplicationVid { get; set; }
        public int ApplicationServiceStatus { get; set; }
        public string ApplicationTypeEquipment { get; set; }
        public string ApplicationProblem { get; set; }
        public Nullable<System.DateTime> ApplicationDateClosing { get; set; }
        public int ApplicationTypeProblem { get; set; }
    
        public virtual TableServiceType TableServiceType { get; set; }
        public virtual TableProblemType TableProblemType { get; set; }
        public virtual TableService TableService { get; set; }
        public virtual TableServiceStatus TableServiceStatus { get; set; }
        public virtual TableServiceVid TableServiceVid { get; set; }
    }
}
