//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableClient
    {
        public string ClientID { get; set; }
        public string ClientSurname { get; set; }
        public string ClientName { get; set; }
        public string ClientPatronymic { get; set; }
        public int ClientGenre { get; set; }
        public System.DateTime ClientBirthday { get; set; }
        public string ClientNumberPhone { get; set; }
        public string ClientEmail { get; set; }
        public int ClientAddressRegistration { get; set; }
        public int ClientAddressAccommodation { get; set; }
        public string ClientTreaty { get; set; }
        public int ClientEquipment { get; set; }
    
        public virtual TableEquipment TableEquipment { get; set; }
        public virtual TableGender TableGender { get; set; }
        public virtual TablePassport TablePassport { get; set; }
        public virtual TableTreaty TableTreaty { get; set; }
    }
}
